name: Build Kernel
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi ccache

      - name: Build Kernel
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          export USE_CCACHE=1
          
          # 1. Pehle folder check karte hain ki file kahan hai
          echo "Listing all files in configs:"
          ls -R arch/arm/configs/
          
          # 2. Ab build shuru karte hain (agar file direct folder mein hogi toh ye chal jayega)
          make O5lteswa_LP_defconfig ARCH=arm
          make -j$(nproc) ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-

      - name: Upload zImage
        uses: actions/upload-artifact@v4
        with:
          name: zImage
          path: arch/arm/boot/zImage
          
